version: '3'

services:
    app:
        container_name: golang
        build: ./docker/app
        tty: true
        volumes:
            - ./:/www/workbookstock
        ports:
            - '8080:8080'
    db:
        container_name: postgres
        build: ./docker/db
        tty: true
        environment:
            - POSTGRES_DB=workbookstock
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - ./model/initdb:/docker-entrypoint-initdb.d
    pgadmin:
        image: dpage/pgadmin4:5.0
        container_name: pgadmin
        tty: true
        ports:
            - 8000:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=pguser
            - PGADMIN_DEFAULT_PASSWORD=password
        depends_on:
            - db
    front:
        container_name: nodejs
        build: ./docker/js
        tty: true
        ports:
            - '3000:3000'
        volumes:
            - ./views/build:/workbookstock/build
            - ./views/src:/workbookstock/src
            - ./views/public:/workbookstock/public
