# デプロイ時に変更
dbConnection:
  dbDriver: postgres
  dsn: host=postgres user=pguser password=password dbname=workbookstock sslmode=disable
initUsers:
  - email: tester@admin.com
    name: tester
    password: admintest
