FROM node:16

RUN yarn global add create-react-app
RUN yarn add react-router-dom
RUN yarn add react-cookie
RUN yarn add react-bootstrap bootstrap
RUN yarn add axios

RUN npx create-react-app workbookstock
WORKDIR /workbookstock